### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by jugendhacker** [uestueab/app-thesis#11]
We received an inclusion request over at [F-Droid](https://gitlab.com/fdroid/rfp/-/issues/1919). To get this app into F-Droid multiple things need to be done.

First it would be nice to have the approval of the original author (which seems to be @uestueab here).

The other things are more technical nature:
* [x] Releases should be tagged, so that F-Droid could know which specific code they need to build the app
* [x] Please add [Fastlane filestructure](https://gitlab.com/-/snippets/1895688) so that F-Droid build servers could get the metadata of your app directly from your repo, which drastically reduces maintenance effort for the F-Droid team
* [x] Please upgrade you gradle wrapper, which should be as simple as `./gradlew wrapper --gradle-version 6.7.1 --gradle-distribution-sha256-sum 3239b5ed86c3838a37d983ac100573f64c1f3fd8e1eb6c89fa5f9529b5ec091d`

**Comment by uestueab** [comment]
Thanks, i will look into this!

**Comment by uestueab** [comment]
@jugendhacker Thanks, will look into this!

**Comment by uestueab** [comment]
@jugendhacker Alright, i took care of all the tasks. Hit me up, if something is missing/requires further intervention.

**Comment by jugendhacker** [comment]
Congrats, F-Droid did [build it successfully](https://monitor.f-droid.org/builds/log/com.thesis.yatta/2), now we just need to wait for signing and deployment. If this works I'll close this issue here.

**Comment by uestueab** [comment]
@jugendhacker Thats awesome, appreciate it! Could you tell me, how to deploy later versions of the app on F-Droid. Do i follow  the same steps via RFP-issues?

**Comment by jugendhacker** [comment]
No you don't have to do anything, it's just a matter of time, because someone needs to transfer the build to an air gaped machine for signing and back and then it will get uploaded into the repo

**Comment by jugendhacker** [comment]
The app now made it into the repo: https://f-droid.org/packages/com.thesis.yatta/

**Comment by jugendhacker** [comment]
You could btw include a nice "Get it on F-Droid"-Badge in your readme, see https://gitlab.com/fdroid/artwork/tree/master/badge#badge

**Comment by uestueab** [comment]
@jugendhacker These are great news! Thank you for your efforts :+1:
